[package]
name = "verifiable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
#rand_core = { version = "0.6", default-features = false }
derive-where = "1.2"
bounded-collections = "0.1.8"

parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive","max-encoded-len"] }
scale-info = { version = "2.7.0", default-features = false, features = ["derive"] }
schnorrkel = "0.10.2"
getrandom = { version = "0.2.11", features = ["js"] }
wasm-bindgen = "0.2.89"
js-sys = "0.3.66"

#ark-scale = { git = "https://github.com/w3f/ark-scale.git", default-features = false, features = ["ec"] }
#bandersnatch_vrfs = { git = "https://github.com/w3f/ring-vrf.git" }